#!/bin/bash

dir=$1

rm -rf /tmp/homebrew_install_private_folder_copies
mkdir /tmp/homebrew_install_private_folder_copies

cd /tmp/homebrew_install_private_folder_copies
git init

while true; do
    cp -a /private/tmp/unixodbc-* /tmp/homebrew_install_private_folder_copies
    git add .
    git commit -m "changes"
    sleep 1
done
